# Site settings
title: Cześc, tu Paweł
email: filmypawla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Recenzje, opinie, oświadczenia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: xx

# Build settings
markdown: kramdown
